name: Manual Trigger Pipeline

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch the last two commits to compare changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Clone External Repository
        run: |
          git clone --branch test-CICD https://$USERNAME_GITHUB:$TOKEN_GITHUB@github.com/revvco/m2x-nebula.git
          cd m2x-nebula
          
    
      - name: Find changed folder and run script
        run: |
          # Get a list of all changed files
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # Extract unique directories in the endpoint folder
          CHANGED_DIRS=$(echo "$CHANGED_FILES" | grep '^endpoint/' | cut -d '/' -f 2 | sort -u)
          echo "Changed directories in endpoint:"
          echo "$CHANGED_DIRS"

          if [ -z "$CHANGED_DIRS" ]; then
            echo "No changes detected in any endpoint subdirectory."
            exit 0
          fi

          for DIR in $CHANGED_DIRS; do
            echo "Processing directory: endpoint/$DIR"
            cd endpoint/$DIR
            
            # Log the command being used to install dependencies
            if [ -f "requirements.txt" ]; then
              echo "Running: pip install -r requirements.txt in endpoint/$DIR"
              pip install -r requirements.txt
            else
              echo "No requirements.txt found in endpoint/$DIR"
            fi
            
            # Log the command being used to run the script
            if [ -f "deploy.sh" ]; then
              echo "Running: deploy.sh in endpoint/$DIR"
              bash deploy.sh
            else
              echo "No deploy.sh script found in endpoint/$DIR"
            fi

            cd -  # Return to the previous directory
          done
